name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18

      # - name: Install dependencies
      #   run: npm ci --legacy-peer-deps

      # - name: Build project
      #   working-directory: ./view
      #   run: npm run build

      # - name: Publish to npm
      #   working-directory: ./view
      #   run: npm publish --output-dir=./build

      - name: SCP build to server
        # working-directory: ./view
        env:
          SERVER: ${{ secrets.SSH_SERVER }}
          USER: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$KEY" | tee key.pem > /dev/null
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no -r ./view $USER@$SERVER:/temp/app
          rm key.pem